const catchErrors = (fn: Function) => {}
export default catchErrors
